#version: '3'
#
#services:
#  mongo:
#    image: mongo:6.0
#    container_name: mongo
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo_data:/data/db
#    environment:
#      MONGO_INITDB_DATABASE: financeStockData
#
#  airflow-webserver:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: airflow-webserver
#    depends_on:
#      - mongo
##      - postgres
#    environment:
#      - AIRFLOW__CORE__LOAD_EXAMPLES=False
#      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
#      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
#    volumes:
#      - ./dags:/opt/airflow/dags
#      - ./output:/opt/airflow/output
#      - ./notebooks:/opt/airflow/notebooks
#    ports:
#      - "8082:8080"  # Change port to avoid conflicts
#    command: ["webserver"]
#
#  airflow-scheduler:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: airflow-scheduler
#    depends_on:
#      - mongo
##      - postgres
#    environment:
#      - AIRFLOW__CORE__LOAD_EXAMPLES=False
#      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
#      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mongodb://mongo:27017/financeStockData
#    volumes:
#      - ./dags:/opt/airflow/dags
#      - ./output:/opt/airflow/output
#      - ./notebooks:/opt/airflow/notebooks
#    command: ["scheduler"]
#
#volumes:
#  mongo_data:
#    driver: local

version: '3'

services:
  # PostgreSQL for Airflow Metadata
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MongoDB for External Data
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: financeStockData

  # Airflow Webserver
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-webserver
    depends_on:
      - postgres
      - mongo
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./output:/opt/airflow/output
      - ./notebooks:/opt/airflow/notebooks
    ports:
      - "8082:8080"
    command: ["webserver"]

  # Airflow Scheduler
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    depends_on:
      - postgres
      - mongo
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./output:/opt/airflow/output
      - ./notebooks:/opt/airflow/notebooks
    command: ["scheduler"]

volumes:
  mongo_data:
    driver: local
  postgres_data:
    driver: local